### ISSUE TITLE
Best Method to Create Super-Admin User Not Clear

### ISSUE THREAD

**Issue by edward-of-clt** [freeipa/freeipa-community-portal#49]
I have tried to provide a role all privileges but get various errors all resembling `invalid 'permission': cannot add permission "System: Read Global Configuration" with bindtype "all" to a privilege`.

However, I need a few users with all permissions for the time being until the IPA servers are stood up completely.

I have looked through Google, various mailing lists however I cannot find a definitive method of creating a user with all permissions to manage and setup our IPA server cluster.

**Comment by tiran** [comment]
This is the wrong place to get help. The community portal project was a project to create a self-service web portal for FreeIPA. Please ask on the FreeIPA users mailing list or IRC channel on Freenode to get help. You can find the address on https://www.freeipa.org/page/Main_Page
